[build]
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "docusaurus start"
  targetPort = 3000
  port = 8888
  functions = "netlify/functions"

[[headers]]
  for = "/private-blog/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  # ensure Netlify serves the CMS config YAML file directly (avoid SPA rewrite)
  from = "/admin/config.yml"
  to = "/admin/config.yml"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

