import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;

// <AUTO-GENERATED-TAGS-SIDEBAR>
// </AUTO-GENERATED-TAGS-SIDEBAR>
